// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgRkELVLT4k0iJS6HYflaXm_v6Ej-Nkm0',
    appId: '1:282359351317:web:81a8e9fecc7764a049261c',
    messagingSenderId: '282359351317',
    projectId: 'ksv-hackathon',
    authDomain: 'ksv-hackathon.firebaseapp.com',
    storageBucket: 'ksv-hackathon.firebasestorage.app',
    measurementId: 'G-ZRFRM3KED3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWfEHXJmYjfqNw-oyFhOPFqlWGEbA_vCY',
    appId: '1:282359351317:android:174c240c89a9d52d49261c',
    messagingSenderId: '282359351317',
    projectId: 'ksv-hackathon',
    storageBucket: 'ksv-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANOGZ_HwFXfJuEPmxtdE9s_pSKw-QsIys',
    appId: '1:282359351317:ios:cf378350aabf454b49261c',
    messagingSenderId: '282359351317',
    projectId: 'ksv-hackathon',
    storageBucket: 'ksv-hackathon.firebasestorage.app',
    iosBundleId: 'com.vendorbridge.vendorBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANOGZ_HwFXfJuEPmxtdE9s_pSKw-QsIys',
    appId: '1:282359351317:ios:cf378350aabf454b49261c',
    messagingSenderId: '282359351317',
    projectId: 'ksv-hackathon',
    storageBucket: 'ksv-hackathon.firebasestorage.app',
    iosBundleId: 'com.vendorbridge.vendorBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgRkELVLT4k0iJS6HYflaXm_v6Ej-Nkm0',
    appId: '1:282359351317:web:856d5efc8bcc14cb49261c',
    messagingSenderId: '282359351317',
    projectId: 'ksv-hackathon',
    authDomain: 'ksv-hackathon.firebaseapp.com',
    storageBucket: 'ksv-hackathon.firebasestorage.app',
    measurementId: 'G-76SJFSLMSZ',
  );
}
